<?xml version="1.0" encoding="UTF-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="Floribot">

<!-- Wagenparameter -->
<xacro:property name="height_wagen" value="0.363" />
<xacro:property name="width_wagen" value="0.213" />
<xacro:property name="len_wagen_vorne" value="0.635" />
<xacro:property name="len_wagen_hinten" value="0.605" />

<!-- Ghost Elements -->
<xacro:property name="ghost_size" value="0.01" />
<xacro:property name="base2Vorderwagen" value="0.04" />
<xacro:property name="Hinterwagenghost2Hinterwagen" value="0.025" />

<!-- Reifenparameter -->
<xacro:property name="wheel_radius" value="0.140" />
<xacro:property name="wheel_thickness" value="0.09" />
<xacro:property name="x_joint_wheel_front" value="0" />
<xacro:property name="y_joint_wheel_front" value="0.167" />
<xacro:property name="x_joint_wheel_back" value="0" />
<xacro:property name="y_joint_wheel_back" value="0.167" />

<!-- Laserparameter -->
<xacro:property name="x_laser_front" value="0.305" />
<xacro:property name="x_laser_back" value="-0.33" />
<xacro:property name="laser_height" value="0.03" />

<!-- Kameraparameter -->
<xacro:property name="x_camera_front" value="0.3220" />
<xacro:property name="x_camera_back" value="-0.347" />
<xacro:property name="camera_height" value="0.267" />
<xacro:property name="camera_angle" value="0.26" />


<!--Verbindungsgelenkparameter (Skizze: |Vorderwagen|I==|Hinterwagen| -> I: Vertikaler Teil, ==: Horizontaler Teil) -->
<xacro:property name="radius" value="0.008" />
<xacro:property name="vertikal_length" value="0.06" />
<xacro:property name="horizontal_length" value="0.055" />
<xacro:property name="WheelJoint2MidJoint" value="0.383" />
<xacro:property name="JointHeight" value="0.015" />

<!-- Hinzufuegen des Laserscanners -->
<xacro:include filename="$(find sick_scan)/urdf/sick_scan.urdf.xacro" />
<xacro:include filename="$(find realsense2_description)/urdf/_d435i.urdf.xacro" />

<!-- Makro fuer Wheel Tranmission -->
<xacro:macro name="wheelTransGaz" params="position">
  <transmission name="joint_${position}_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="joint_${position}">
          <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        </joint>
        <actuator name="joint_${position}_motor">
          <hardwareInterface>hardware_interface/VelocityActuatorInterface</hardwareInterface>
          <mechanicalReduction>1</mechanicalReduction>
        </actuator>
  </transmission>

  <!-- hardware_interface/VelocityJointInterface -->

  <gazebo reference="${position}">
    <mu1 value="0.5"/>
    <mu2 value="0.5"/>
    <kp value="10000000.0" />
    <kd value="1.0" />
    <fdir1 value="1 0 0"/>
    
  </gazebo> 

</xacro:macro>

  <!-- Base Link -->
  <link name="base_link">
      <visual>
    	  <origin xyz="0 0 ${wheel_radius + ghost_size}" rpy="0 0 0"/>
        <axis xyz="0 0 0"/>
          <geometry>
              <box size="${ghost_size} ${ghost_size} ${ghost_size}"/>
          </geometry>
          <material name="c">
              <color rgba="0 0.9 0.9 1.0"/>
          </material>
      </visual>
  </link>

   <!-- Gelenk zwischen Vorderwagen und base_link -->
  <joint name="base_zu_Vorderwagen" type="fixed">
       <parent link="base_link"/>
       <child link="Vorderwagen"/>
	   <origin xyz="${-base2Vorderwagen} 0 0"/>
  </joint>
  
  <!-- Vorderwagen -->
  <link name="Vorderwagen">
      <visual>
    	  <origin xyz="-${len_wagen_vorne/2+0.0255} 0 -${wheel_radius}" rpy="0 0 0"/>
        <axis xyz="0 0 0"/>
          <geometry>
              <!-- <box size="${len_wagen_vorne} ${width_wagen} ${height_wagen}"/> -->
              <mesh filename="package://floribot_simulation/meshes/Vorderwagen.stl" scale="0.001 0.001 0.001" />
          </geometry>
          <material name="c">
              <color rgba="0 0.9 0.9 1.0"/>
          </material>
      </visual>
      <collision>
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
		    <geometry>
              <box size="${len_wagen_vorne} ${width_wagen} ${height_wagen}"/>
            </geometry>
	  </collision>
	  <inertial>
    <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
		<mass value="33"/>
        <inertia ixx="1.286541" ixy="0.0" ixz="0.0" iyy="0.457810" iyz="0.0" izz="1.063241"/>
      </inertial>
  </link>

  <!-- Kamera vorne-->
  <xacro:sensor_d435i name="front_camera" parent="base_link">
    <origin xyz="${x_camera_front} 0 ${camera_height}" rpy="0 ${camera_angle} 0"/>
  </xacro:sensor_d435i>

  <link name="CameraFrontPositiv">
      <visual>
    	  <origin xyz="${len_wagen_vorne/2-0.06} -0.0225 ${height_wagen*2/3+0.033}" rpy="0 1.57 0"/>
        <axis xyz="0 0 0"/>
          <geometry>
              <!-- <box size="${len_wagen_vorne} ${width_wagen} ${height_wagen}"/> -->
              <mesh filename="package://floribot_simulation/meshes/Anschluss_Item_positiv.stl" scale="0.001 0.001 0.001" />
          </geometry>
          <material name="c">
              <color rgba="0 0.9 0.9 1.0"/>
          </material>
      </visual>
	  <inertial>
		<mass value="0.1"/>
        <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
      </inertial>
  </link>

  <joint name="jointCameraFrontPositiv" type="fixed">
       <parent link="base_link"/>
       <child link="CameraFrontPositiv"/>
	   <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <link name="CameraFrontNegativ">
      <visual>
    	  <origin xyz="${len_wagen_vorne/2} -0.006 ${height_wagen*2/3+0.0410}" rpy="${-camera_angle-1.57} 0 -1.57"/>
        <axis xyz="0 0 0"/>
          <geometry>
              <!-- <box size="${len_wagen_vorne} ${width_wagen} ${height_wagen}"/> -->
              <mesh filename="package://floribot_simulation/meshes/Anschluss_Item_negativ.stl" scale="0.001 0.001 0.001" />
          </geometry>
          <material name="c">
              <color rgba="0 0.9 0.9 1.0"/>
          </material>
      </visual>
	  <inertial>
		<mass value="0.1"/>
        <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
      </inertial>
  </link>

  <joint name="jointCameraFrontNegativ" type="fixed">
       <parent link="CameraFrontPositiv"/>
       <child link="CameraFrontNegativ"/>
	   <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <!-- Laserscanner vorne -->
  <joint name="joint_front_laser" type="fixed">
       <parent link="base_link"/>
       <child link="front_laser_mount_link"/>
	   <origin xyz="${x_laser_front} 0 ${laser_height}" rpy="3.14 0 0"/>
  </joint>
  
  <xacro:sick_tim_5xx name="front_laser" ros_topic="laser_scanner_front"/>


 <!-- Gelenk zwischen Vorderwagen und Verbindungsstueck -->
  <joint name="body_angle" type="revolute">
       <axis xyz="0 0 1"/>
       <limit effort="1.0" lower="-1.57" upper="1.57" velocity="0.5"/>
       <parent link="base_link"/>
       <child link="Gelenkteil_1"/>
	   <origin xyz="${-WheelJoint2MidJoint} 0 -${JointHeight}"/>
  </joint>
  
 <transmission name="body_angle_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="body_angle">
          <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        </joint>
        <actuator name="body_angle_motor">
          <mechanicalReduction>1</mechanicalReduction>
        </actuator>
  </transmission>


 <!-- Verbindungsstueck 1 -->   
   <link name="Gelenkteil_1">
      <visual>
    	  <origin xyz="0 0 0" rpy="0 0 0"/>
        <axis xyz="0 0 0"/>
          <geometry>
              <cylinder length="${vertikal_length}" radius="${radius}"/>
          </geometry>
          <material name="r">
              <color rgba="0.9 0 0 1.0"/>
          </material>
      </visual>
	  <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
		    <geometry>
              <cylinder length="${vertikal_length}" radius="${radius}"/>
            </geometry>
	  </collision>
	  <inertial>
		<mass value="0.01"/>
        <inertia ixx="0.000004" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.000004"/>
      </inertial>
  </link>

 <!-- Gelenk zwischen den beiden Verbindungsstuecken -->
  <joint name="Gelenk" type="revolute">
  <axis xyz="1 0 0"/>
       <limit effort="1.0" lower="-1.57" upper="1.57" velocity="0.5"/>-
       <parent link="Gelenkteil_1"/>
       <child link="Gelenkteil_2"/>
	   <origin xyz="${-horizontal_length/2 - radius} 0 0"/>
  </joint>

 <!-- Verbindungsstueck 2 -->
  <link name="Gelenkteil_2">
      <visual>
    	  <origin xyz="0 0 0" rpy="0 1.57 0"/>
        <axis xyz="0 0 0.025"/>
          <geometry>
              <cylinder length="${horizontal_length}" radius="${radius}"/>
          </geometry>
          <material name="r">
              <color rgba="0.9 0 0 1.0"/>
          </material>
      </visual>
	  <collision>
      <origin xyz="0 0 0" rpy="0 1.57 0"/>
      <geometry>
        <cylinder length="${horizontal_length}" radius="${radius}"/>
      </geometry>
	  </collision>
	  <inertial>
		<mass value="0.01"/>
        <inertia ixx="0.000004" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.000004"/>
      </inertial>
  </link>

 <!-- Gelenk zwischen Verbindungsstueck 2 und Hinterwagen -->
  <joint name="Gelenkteil_2_zu_Hinterwagen" type="fixed">
       <parent link="Gelenkteil_2"/>
       <child link="Hinterwagen_ghost"/>
	   <origin xyz="${-WheelJoint2MidJoint + vertikal_length/2} 0 ${JointHeight}"/>
  </joint>

  <!-- Hinterwagen ghost -->
  <link name="Hinterwagen_ghost">
      <visual>
    	  <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
        <axis xyz="0 0 0"/>
          <geometry>
              <box size="${ghost_size} ${ghost_size} ${ghost_size}"/>
          </geometry>
          <material name="b">
              <color rgba="0 0 0.9 1.0"/>
          </material>
      </visual>
      <collision>
      <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
		    <geometry>
              <box size="${ghost_size} ${ghost_size} ${ghost_size}"/>
            </geometry>
	  </collision>
	  <inertial>
    <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
		<mass value="0.001"/>
        <inertia ixx="1.369982" ixy="0.0" ixz="0.0" iyy="0.487502" iyz="0.0" izz="1.132200"/>
      </inertial>
  </link>

  <!-- Gelenk zwischen Ghost und Hinterwagen -->
  <joint name="Hinterwagen_ghost_zu_Hinterwagen" type="fixed">
       <parent link="Hinterwagen_ghost"/>
       <child link="Hinterwagen"/>
	   <origin xyz="${Hinterwagenghost2Hinterwagen} 0 0"/>
  </joint>

 <!-- Hinterwagen -->
  <link name="Hinterwagen">
      <visual>
    	  <origin xyz="${len_wagen_hinten/2+0.056} 0 -${wheel_radius}" rpy="0 0 0"/>
        <axis xyz="0 0 0"/>
          <geometry>
              <!--<box size="${len_wagen_hinten} ${width_wagen} ${height_wagen}"/>-->
              <mesh filename="package://floribot_simulation/meshes/Hinterwagen.stl" scale="0.001 0.001 0.001" />
          </geometry>
          <material name="b">
              <color rgba="0 0 0.9 1.0"/>
          </material>
      </visual>
	  <collision>
      <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
		    <geometry>
              <box size="${len_wagen_hinten} ${width_wagen} ${height_wagen}"/>
            </geometry>
	  </collision>
	  <inertial>
    <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
		<mass value="33"/>
        <inertia ixx="1.369982" ixy="0.0" ixz="0.0" iyy="0.487502" iyz="0.0" izz="1.132200"/>
      </inertial>
  </link>

  <!-- Kamera hinten-->
  <xacro:sensor_d435i name="rear_camera" parent="Hinterwagen">
    <origin xyz="${x_camera_back} 0 ${camera_height}" rpy="0 ${camera_angle} 3.14"/>
  </xacro:sensor_d435i>

  <link name="CameraRearPositiv">
      <visual>
    	  <origin xyz="${-len_wagen_hinten/2+0.021} +0.0225 ${height_wagen*2/3+0.033}" rpy="0 1.57 3.141"/>
        <axis xyz="0 0 0"/>
          <geometry>
              <!-- <box size="${len_wagen_vorne} ${width_wagen} ${height_wagen}"/> -->
              <mesh filename="package://floribot_simulation/meshes/Anschluss_Item_positiv.stl" scale="0.001 0.001 0.001" />
          </geometry>
          <material name="c">
              <color rgba="0 0.9 0.9 1.0"/>
          </material>
      </visual>
	  <inertial>
		<mass value="0.1"/>
        <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
      </inertial>
  </link>

  <joint name="jointCameraRearPositiv" type="fixed">
       <parent link="Hinterwagen"/>
       <child link="CameraRearPositiv"/>
	   <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <link name="CameraRearNegativ">
      <visual>
    	  <origin xyz="${-len_wagen_hinten/2-0.04} +0.006 ${height_wagen*2/3+0.0410}" rpy="${-camera_angle-1.57} 0 1.57"/>
        <axis xyz="0 0 0"/>
          <geometry>
              <!-- <box size="${len_wagen_vorne} ${width_wagen} ${height_wagen}"/> -->
              <mesh filename="package://floribot_simulation/meshes/Anschluss_Item_negativ.stl" scale="0.001 0.001 0.001" />
          </geometry>
          <material name="c">
              <color rgba="0 0.9 0.9 1.0"/>
          </material>
      </visual>
	  <inertial>
		<mass value="0.1"/>
        <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
      </inertial>
  </link>

  <joint name="jointCameraRearNegativ" type="fixed">
       <parent link="CameraRearPositiv"/>
       <child link="CameraRearNegativ"/>
	   <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  
  <!-- Laserscanner hinten -->
  <joint name="joint_rear_laser" type="fixed">
       <parent link="Hinterwagen"/>
       <child link="rear_laser_mount_link"/>
	   <origin xyz="${x_laser_back} 0 ${laser_height}" rpy="3.14 0 3.14"/>
  </joint>
  
  <xacro:sick_tim_5xx name="rear_laser" ros_topic="laser_scanner_rear"/>

 <!-- Gelenk zwischen Vorderwagen und Rad VL-->
  <joint name="joint_frontLeft" type="continuous">
       <parent link="base_link"/>
       <child link="frontLeft"/>
       <axis xyz="0 1 0"/>
       <origin xyz="${x_joint_wheel_front} ${y_joint_wheel_front} 0"/>
        <limit effort="1.0" velocity="14.2857" />
  </joint>

<!-- Transmission -->
  <xacro:wheelTransGaz position="frontLeft" />

 <!-- Rad VL -->
  <link name="frontLeft">
      <visual>
    	  <origin xyz="0 -${wheel_thickness/2-0.0095} 0" rpy="1.57 0 0"/>
        <axis xyz="0 0 0"/>
          <geometry>
              <!-- <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>-->
              <mesh filename="package://floribot_simulation/meshes/Reifen.stl" scale="0.001 0.001 0.001" />
          </geometry>
          <material name="r">
              <color rgba="0.9 0 0 1.0"/>
          </material>
      </visual>
	  <collision>
    <origin xyz="0 0 0" rpy="1.57 0 0"/>
		    <geometry>
              <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
            </geometry>
	  </collision>
	  <inertial>
		<mass value="2.4"/>
        <inertia ixx="0.013" ixy="0.0" ixz="0.0" iyy="0.023" iyz="0.0" izz="0.013"/>
      </inertial>
  </link>

 <!-- Gelenk zwischen Vorderwagen und Rad VR -->
  <joint name="joint_frontRight" type="continuous">
       <parent link="base_link"/>
       <child link="frontRight"/>
       <axis xyz="0 1 0"/>
       <origin xyz="${x_joint_wheel_front} -${y_joint_wheel_front} 0"/>
       <limit effort="1.0" velocity="14.2857" />
  </joint>

<!-- Transmission -->
  <xacro:wheelTransGaz position="frontRight" />

<!-- Rad VR -->
  <link name="frontRight">
      <visual>
    	  <origin xyz="0 -${wheel_thickness/2 - 0.0105} 0" rpy="1.57 0 0"/>
        <axis xyz="0 0 0"/>
          <geometry>
              <!-- <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/> -->
              <mesh filename="package://floribot_simulation/meshes/Reifen.stl" scale="0.001 0.001 0.001" />
          </geometry>
          <material name="r">
              <color rgba="0.9 0 0 1.0"/>
          </material>
      </visual>
	  <collision>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
		    <geometry>
              <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
            </geometry>
	  </collision>
	  <inertial>
		<mass value="2.4"/>
        <inertia ixx="0.013" ixy="0.0" ixz="0.0" iyy="0.023" iyz="0.0" izz="0.013"/>
      </inertial>
  </link>

<!-- Gelenk zwischen Hinterwagen und Rad HR -->
  <joint name="joint_rearRight" type="continuous">
       <parent link="Hinterwagen_ghost"/>
       <child link="rearRight"/>
       <axis xyz="0 1 0"/>
       <origin xyz="${x_joint_wheel_back} -${y_joint_wheel_back} 0"/>
       <limit effort="1.0" velocity="14.2857" />
  </joint>

<!-- Transmission -->
  <xacro:wheelTransGaz position="rearRight" />

<!-- Rad HR -->
  <link name="rearRight">
      <visual>
    	  <origin xyz="0 -${wheel_thickness/2 - 0.0105} 0" rpy="1.57 0 0"/>
        <axis xyz="0 0 0"/>
          <geometry>
              <!-- <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/> -->
              <mesh filename="package://floribot_simulation/meshes/Reifen.stl" scale="0.001 0.001 0.001" />
          </geometry>
          <material name="r">
              <color rgba="0.9 0 0 1.0"/>
          </material>
      </visual>
	  <collision>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
		    <geometry>
              <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
            </geometry>
	  </collision>
	  <inertial>
		<mass value="2.4"/>
        <inertia ixx="0.013" ixy="0.0" ixz="0.0" iyy="0.023" iyz="0.0" izz="0.013"/>
    </inertial>
  </link>

<!-- Gelenk zwischen Hinterwagen und Rad HL -->
  <joint name="joint_rearLeft" type="continuous">
       <parent link="Hinterwagen_ghost"/>
       <child link="rearLeft"/>
       <axis xyz="0 1 0"/>
       <origin xyz="${x_joint_wheel_back} ${y_joint_wheel_back} 0"/>
       <limit effort="1.0" velocity="14.2857" />
  </joint>

<!-- Transmission -->
  <xacro:wheelTransGaz position="rearLeft" />

<!-- Rad HL -->
  <link name="rearLeft">
      <visual>
    	  <origin xyz="0 -${wheel_thickness/2-0.0095}  0" rpy="1.57 0 0"/>
        <axis xyz="0 0 0"/>
          <geometry>
              <!-- <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/> -->
              <mesh filename="package://floribot_simulation/meshes/Reifen.stl" scale="0.001 0.001 0.001" />
          </geometry>
          <material name="r">
              <color rgba="0.9 0 0 1.0"/>
          </material>
      </visual>
	  <collision>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
		    <geometry>
              <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
            </geometry>
	  </collision>
	  <inertial>
		<mass value="2.4"/>
        <inertia ixx="0.013" ixy="0.0" ixz="0.0" iyy="0.023" iyz="0.0" izz="0.013"/>
      </inertial>
  </link>

<!-- Gazebo plugin for ROS Control -->
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>floribot</robotNamespace>
    </plugin>
  </gazebo>

</robot>
